### ISSUE TITLE
SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

### ISSUE THREAD

**Issue by Naereen** [JoshLankford/WakaTimeCLI#17]
Hi,
I loved this extension a few years ago, and haven't used in a long time (I talk about it on my website, [here](https://perso.crans.org/besson/wakatime.en.html#let-us-finish-on-a-bonus-read-your-wakatime-stats-from-the-command-line)).

I reinstalled it, and added the API through the (undocumented?) `wakatime -api` command, it worked.

But when try to get, for instance, `wakatime -w` weekly report, I encountered this error:
```bash
$ wakatime -w
error -  { Error: write EPROTO 139628127275904:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:s23_clnt.c:802:

    at _errnoException (util.js:1022:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:880:14) code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
```

Thanks in advance.

**Comment by Naereen** [comment]
@JoshLankford @alanhamlett ?
